name: "Sync AWS Secrets Manager"
description: "Sync AWS Secrets Manager with a JSON file"

branding:
  icon: database
  color: blue

inputs:
  aws_access_key_id:
    description: "AWS Access Key ID"
    required: true
  aws_secret_access_key:
    description: "AWS Secret Access Key"
    required: true
  aws_region:
    description: "AWS Region"
    required: true
  secret_name:
    description: "AWS Secret Name"
    required: true
  json_file_path:
    description: "Path to the JSON file containing secret data"
    required: true
  create_secret:
    description: "Flag to create the given secret if not exist before execute sync"
    required: false
  dry_run:
    description: "Dry run mode (preview changes without modifying the secret)"
    required: false
  show_values:
    description: "Show secret values when viewing change set"
    required: false
  exclude:
    description: "List of regular expressions that determines if a secret key should be excluded from sync"
    required: false

runs:
  using: "docker"
  image: "Dockerfile"
